version: '2.4'
services:
  ros2_playground:
    container_name: ros2_with_everything
    image: ros2_with_everything
    environment:
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: 1
      ROS_LOCALHOST_ONLY: 1
      QT_X11_NO_MITSHM: '1'
    network_mode: host
    privileged: true
    stdin_open: true
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - ../workdir:/root/ros2_ws/src/localxhos
    command: >
      bash -c "
        source /root/ros2_ws/install/setup.bash
        tail -f /dev/null"